baseURL = 'https://blogs.bobbysmiles.xyz/'
languageCode = 'en-us'
title = "Bobby's Headspace"

theme = "re-terminal"

[params]
	themeColor = "green"

[params.author]
		name = 'Bobby Smiles'
		email = 'smiles@bobbysmiles.xyz'

[languages]
  [languages.en.params]
    languageName = "English"
    title = "Bobby's Headspace"
    subtitle = "Blog where I can post whatever interests me"
    owner = "LordA2117"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "Bobby's Headspace"
      logoHomeLink = "/"

    [languages.en.menu]
      # Submenus is available since v2.1.0
      # [[languages.en.menu.main]]
      #   identifier = "submenuParent"
      #   name = "Submenu"
      # [[languages.en.menu.main]]
      #   parent = "submenuParent"
      #   identifier = "anItem"
      #   name = "AnItem"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/LordA2117"
      [[languages.en.menu.main]]
        identifier = "youtube"
        name = "YouTube"
        url = "https://www.youtube.com/@LazyCSE"
			[[languages.en.menu.main]]
				identifier = "portfolio"
				name = "Portfolio"
				url = "https://portfolio.bobbysmiles.xyz"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
